data:
  dataloader: {batch_size: 32, class_balance: true, data_workers: 2}
  dataset: {class_share: 10, class_total: 10, source: mnist, target: syn}
test: {test_interval: 500, test_only: false}
train: {update_freq: 100, lr: 0.001, min_step: 5000, momentum: 0.9, weight_decay: 0.0005}


